# Generated by Django 5.2.12 on 2026-03-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='organic_certified',
            field=models.BooleanField(default=False),
        ),
    ]
